Fb lsdv3896 1/pannel tabs
HumanSignal/label-studio-frontend pull request #1241
Opened 2023-03-14 18:20 UTC by Travis1282

### PR fulfills these requirements
- [X] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [X] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [X] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [X] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [X] Product design
- [X] Frontend

### Describe the reason for change
New Feature for tabs in panels, draggable across windows

#### What does this fix?
_(if this is a bug fix)_

#### What is the new behavior?
tabs can be pulled out of panels and rearranged or collapsed 

#### What is the current behavior?
currently there are no tabs on panels 

#### What libraries were added/updated?
N/A

#### Does this change affect performance?
N/A

#### Does this change affect security?
N/A

#### What alternative approaches were there?
_(briefly list any if applicable)_

#### What feature flags were used to cover this change?
fflag_feat_front_dev_3873_labeling_ui_improvements_short

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [X] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [X] unit

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_

2023-03-15 10:56 UTC, yyassi-heartex commented
/git merge master

2023-03-15 18:02 UTC, bmartel commented on src/components/AnnotationsCarousel/AnnotationButton.tsx
Something about these changes may be causing a regression from #1096. Just a suspicion it is this change, but it definitely is something related to annotation button functionality. 

https://user-images.githubusercontent.com/2242258/225401784-49b795f3-12e1-4a54-8453-1a788796f761.mov

2023-03-15 18:44 UTC, Travis1282 commented on src/components/AnnotationsCarousel/AnnotationButton.tsx
can you check again? Made updates

2023-03-15 19:22 UTC, bmartel requested changes

2023-03-15 19:22 UTC, bmartel commented on src/components/SidePanels/TabPanels/utils.ts
> +};
Can this be replaced with just using lodash debounce? Not sure what this does exactly as it appears to not be throttling but debouncing the calls.

2023-03-15 19:22 UTC, bmartel commented on src/components/SidePanels/TabPanels/Tabs.tsx
> +      setTimeout(()=> setDragOverSide(undefined), 200);
What is the significance of `200` as a timeout here?

2023-03-15 19:22 UTC, bmartel commented on src/components/SidePanels/TabPanels/Tabs.tsx
> +  useEffect(() => { location.current = { panelKey, tabIndex }; }, [panelKey, tabIndex]);
Suggesting the same here, we don't need the useEffect to assign a ref for purposes of keeping a non stale reference to values in event handlers/callback closures.

```suggestion
  location.current = { panelKey, tabIndex };
```

2023-03-15 19:22 UTC, bmartel commented on src/components/SidePanels/TabPanels/Tabs.tsx
> +  }, [tabRef]);
Is this a dependencies array? References are stable so if it is a dependencies array we would want to probably put nothing here.

2023-03-15 19:22 UTC, bmartel commented on src/components/SidePanels/TabPanels/SideTabsPanels.tsx
> +  }, [eventHandlers, rootRef, regions, regions.selection, currentEntity]);
same thing here, rootRef is a stable reference, it won't trigger dependency arrays.

2023-03-15 19:22 UTC, bmartel commented on src/components/SidePanels/TabPanels/PanelTabsBase.tsx
> +  }, [headerRef, detached, visible, locked]);
Another one with stable refs in a dependency array. `headerRef`

2023-03-15 20:22 UTC, Travis1282 commented on src/components/SidePanels/TabPanels/PanelTabsBase.tsx
> +  useEffect(() => { keyRef.current = key; }, [key]);
much better thanks!

2023-03-16 13:40 UTC, yyassi-heartex commented on src/components/SidePanels/SidePanels.tsx
> +    return isFF(FF_DEV_3873) ? true : Object.values(panelData).find(p => p.alignment === alignment && !p.detached) === undefined;
```suggestion
    return isFF(FF_DEV_3873) || Object.values(panelData).find(p => p.alignment === alignment && !p.detached) === undefined;
```

2023-03-20 21:46 UTC, bmartel approved these changes

2023-09-12 16:40 UTC, closed without merging