feat: LSDV-5297: Sort phrases
HumanSignal/label-studio-frontend pull request #1493
Opened 2023-07-07 17:40 UTC by Travis1282

### PR fulfills these requirements
- [X] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [X] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [X] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [X] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [X] Frontend

### Describe the reason for change
Phrases need to be sorted

#### What does this fix?
This sorts by start time 

#### What is the new behavior?
sorted by start time and null values at the end

#### What is the current behavior?
no sorting

#### What libraries were added/updated?
none

#### Does this change affect performance?
no

#### Does this change affect security?
no

#### What alternative approaches were there?
n/a

#### What feature flags were used to cover this change?
fflag_feat_front_lsdv_e_278_contextual_scrolling_short

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [X] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [X] unit

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_

2023-07-07 19:06 UTC, bmartel requested changes

2023-07-07 19:06 UTC, bmartel commented on src/tags/object/Paragraphs/Phrases.js
> +  const list = contextScroll ? item._value.sort(sortPhrases) : item._value;
We will need this to be sorted within the model level so anywhere that references this data it is the same.

2023-07-10 10:55 UTC, yyassi-heartex commented on src/tags/object/Paragraphs/Phrases.js
> +  const val =  item._value.map((v, idx) => {
minor cleanup
```suggestion
  const val = item._value.map((v, idx) => {
```

2023-07-10 12:53 UTC, bmartel approved these changes
Approving based on the cleanup of the minor observations.

2023-07-20 13:54 UTC, Travis1282 commented
/git merge master

2023-07-24 15:47 UTC, merged