fix: LSDV-5044: Add queTotal to lsfProperties from project
HumanSignal/label-studio-frontend pull request #1554
Opened 2023-09-06 15:28 UTC by Travis1282

### PR fulfills these requirements
- [X] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [X] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [X] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [X] Frontend

### Describe the reason for change
the task count was grabbing the length of the history as a total but this was always equal to the current task. 

#### What does this fix?
This grabs the queue total from the project

#### What is the new behavior?
the queue total should represent the actual number of items

#### What is the current behavior?
always the wrong number

#### What libraries were added/updated?
_(list all with version changes)_

#### Does this change affect performance?
_(if so describe the impacts positive or negative)_

#### Does this change affect security?
_(if so describe the impacts positive or negative)_

#### What alternative approaches were there?
_(briefly list any if applicable)_

#### What feature flags were used to cover this change?
_(briefly list any if applicable)_

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [ ] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_

2023-09-06 22:58 UTC, hlomzik approved these changes

2023-09-18 22:10 UTC, bmartel requested changes

2023-09-18 22:10 UTC, bmartel commented on src/stores/AppStore.js
> +      self.queuePosition += number;
If we are just incrementing or decrementing by 1, this should be clamp(self.queuePosition, 0, self.queueTotal) or the numbers could go wild.

2023-09-18 22:10 UTC, bmartel commented on src/components/BottomBar/CurrentTask.js
> +            <Tooltip name={'task-count'} title={`${store.queuePosition} tasks complete of ${store.queueTotal} total tasks`}>
The queuePosition isn't the number of tasks complete, its the position within the task queue according to the number of tasks available to the annotator, assigned + could be assigned (if in auto mode).

2023-10-04 08:37 UTC, AndrejOros commented
/git merge master

2023-10-05 16:28 UTC, merged