fix: OPTIC-354: Comment draft preserved between annotations
HumanSignal/label-studio-frontend pull request #1652
Opened 2023-12-28 00:23 UTC by Travis1282

### PR fulfills these requirements
- [X] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [X] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [X] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [ ] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [X] Frontend

### Describe the reason for change
[OPTIC-354](https://humansignal.atlassian.net/browse/OPTIC-354)

#### What does this fix?
It persists unsaved drafts between annotations on a task 

#### What is the new behavior?
It persists unsaved drafts between annotations on a task 

#### What is the current behavior?
it would not reset the task when navigating between annotations 

#### What libraries were added/updated?
n/a

#### Does this change affect performance?
n/a

#### Does this change affect security?
no

#### What alternative approaches were there?
none

#### What feature flags were used to cover this change?
none

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [X] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
comments

2023-12-28 11:43 UTC, hlomzik requested changes

2023-12-28 11:43 UTC, hlomzik commented on src/components/SidePanels/DetailsPanel/DetailsPanel.tsx
> +              annotationStore={store.annotation}
`store.annotation`? what is it?

2024-01-02 17:00 UTC, luarmr approved these changes
LGTM

2024-01-03 00:00 UTC, hlomzik approved these changes

2024-01-03 21:18 UTC, merged