fix: DEV-3346: Task history is stored on the backend for the label steam
HumanSignal/label-studio-frontend pull request #872
Opened 2022-09-23 23:47 UTC by juliosgarbi

2022-09-28 14:41 UTC, bmartel requested changes

2022-09-28 14:41 UTC, bmartel commented on src/stores/AppStore.js
> +          ];
Is `taskHistory` a reactive object in mobx, or just a standard array? I would use the builtin array properties if its a mobx reactive value as I believe those are overridden in the case of mobx for reactive bindings propagation and replacing the array could mess up reactivity.

```suggestion
          self.taskHistory.unshift({
            taskId: self.task.id,
            annotationId: null,
          })
```

2022-09-28 16:10 UTC, bmartel approved these changes

2022-11-14 15:08 UTC, hlomzik commented
/git merge master

2023-01-12 14:59 UTC, bmartel approved these changes

2023-09-13 17:16 UTC, hlomzik commented
Implemented with a little different approach in https://github.com/HumanSignal/label-studio-frontend/pull/1181

2023-09-13 17:16 UTC, closed without merging